import logging
import json
from typing import Dict, Any, Optional
from google import genai

from backend.agents.observe_agent import get_api_key
from backend.tools.cpm_engine import get_project_state
from backend.config import MODEL_NAME, use_mock_llm

# Configure logging
logger = logging.getLogger(__name__)

_ADVISORY_DISCLAIMER = (
    "Advisory considerations are general safety best practices generated by AI for "
    "informational purposes only. The regulatory hard stop status is derived deterministically "
    "from the ConstructionOS regulatory knowledge base rules and is not influenced by these advisories."
)

# ---------------------------------------------------------------------------
# MOCK LLM data for safety agent
# ---------------------------------------------------------------------------
_MOCK_SAFETY = {
    "work_at_height": {
        "brief": (
            "[MOCK] Safety Compliance Assessment: Tower Crane mechanical failure classified "
            "as Work at Height (severity 8/10). HARD_STOP issued. BOCW Act Section 40 mandates "
            "mandatory scaffolding and harness checks for all work above 2 metres. All elevated "
            "operations must cease immediately until a full engineering inspection and BOCW compliance "
            "verification is completed. No override is permitted."
        ),
        "advisory_considerations": (
            "- Conduct immediate physical inspection of all harnesses, lanyards, and anchor points before any resumption.\n"
            "- Verify crane hoist mechanism and wire-rope integrity with a certified lifting equipment engineer.\n"
            "- Issue a site-wide toolbox talk covering fall-clearance calculations and emergency rescue protocol."
        ),
    },
    "extreme_weather": {
        "brief": (
            "[MOCK] Safety Compliance Assessment: Heavy weather event classified as Extreme Weather "
            "(severity 6/10). HARD_STOP issued. BOCW Act Section 41B and IMD weather threshold protocols "
            "mandate cessation of all open-site operations during severe weather. Operations suspended until "
            "meteorological all-clear is confirmed by site supervisor."
        ),
        "advisory_considerations": (
            "- Monitor IMD/NDMA alerts hourly and do not resume work until wind speed drops below 45 km/h.\n"
            "- Secure all loose materials, scaffolding panels, and unsecured equipment immediately.\n"
            "- Issue weather-standdown memo to all contractors; log the stoppage in the site diary."
        ),
    },
    "excavation": {
        "brief": (
            "[MOCK] Safety Compliance Assessment: Ambiguous event classified as Excavation category "
            "(severity 3/10). No regulatory rule triggered for this category at this severity. "
            "No HARD_STOP issued — operations may continue with standard precautions."
        ),
        "advisory_considerations": (
            "- Verify trench shoring and shielding stability before allowing personnel near excavation faces.\n"
            "- Conduct atmospheric hazard check (oxygen, CO, methane) at trench entry points.\n"
            "- Ensure physical barriers and warning tape are installed around all open excavation perimeters."
        ),
    },
}


def assess_safety(observe_output: Dict[str, Any], raw_event_text: Optional[str] = None) -> Dict[str, Any]:
    """
    Evaluates safety compliance by matching the event type against active regulatory rules.
    Issues a HARD_STOP if any matching rule is found.
    In mock mode (USE_MOCK_LLM=true), returns deterministic results with no API calls.
    """
    # 1. Handle upstream parse errors
    if observe_output.get("parse_error"):
        logger.warning("Safety assessment halted due to upstream parse error.")
        return {
            "hard_stop": False,
            "triggered_rules": [],
            "brief": "Safety assessment halted: Observe Agent failed to parse the event.",
            "advisory_considerations": "",
            "advisory_disclaimer": _ADVISORY_DISCLAIMER,
            "fallback_mode_active": False,
            "parse_error": True
        }

    event_type = observe_output.get("event_type")
    severity = observe_output.get("severity")

    # 2. Load active regulatory knowledge base rules (always deterministic)
    state, fallback_mode = get_project_state()
    rules = state.get("regulatory_kb", [])

    # 3. Match rules based on trigger condition (always deterministic — not mocked)
    triggered_rules = []
    for rule in rules:
        if rule.get("trigger_condition") == event_type:
            triggered_rules.append({
                "code": rule.get("code"),
                "description": rule.get("description")
            })

    # HARD_STOP is True if any rule trigger condition matches the event type.
    # WARNING: advisory_considerations must never influence hard_stop.
    hard_stop = len(triggered_rules) > 0

    # --- MOCK MODE: skip all Gemini calls, use canned briefs/advisories ---
    if use_mock_llm():
        logger.info("[MOCK MODE] Safety Agent running without Gemini API call.")
        mock_data = _MOCK_SAFETY.get(event_type, {
            "brief": f"[MOCK] Safety evaluation complete. Hard stop: {hard_stop}. Triggered rules: {', '.join([r['code'] for r in triggered_rules]) if triggered_rules else 'none'}.",
            "advisory_considerations": "- Follow standard job safety analysis procedures.\n- Report any hazardous conditions to site supervisor.",
        })
        return {
            "hard_stop": hard_stop,
            "triggered_rules": triggered_rules,
            "brief": mock_data["brief"],
            "advisory_considerations": mock_data["advisory_considerations"],
            "advisory_disclaimer": _ADVISORY_DISCLAIMER,
            "fallback_mode_active": fallback_mode,
            "parse_error": False
        }

    # 4. Generate explanation brief using Gemini (treating the decision as fixed facts)
    api_key = get_api_key()
    if not api_key:
        logger.warning("GEMINI_API_KEY not configured. Safety Agent using offline fallback brief.")
        brief = (
            f"Safety evaluation complete. Hard stop: {hard_stop}. "
            f"Triggered rules: {', '.join([r['code'] for r in triggered_rules]) if triggered_rules else 'none'}."
        )
    else:
        client = genai.Client(api_key=api_key)
        
        prompt = f"""
You are the Safety Agent for ConstructionOS AI.
Your task is to draft a compliance assessment brief explaining a safety event evaluation.

The safety evaluation results are already decided as fixed facts:
- HARD_STOP: {hard_stop} (if True, this is an absolute, non-overridable stop signal for operations)
- Triggered Rules: {json.dumps(triggered_rules)}
- Event Category: {event_type}
- Event Severity: {severity}/10

Raw Jobsite Report Context:
"{raw_event_text or 'No raw text provided.'}"

Please write a brief summary explaining these facts, emphasizing why a hard stop was or was not issued, and reference relevant regulatory norms (such as BOCW Act or Factories Act) as context.
WARNING: Your narrative must be entirely consistent with the fixed facts above (HARD_STOP is {hard_stop}). Do not contradict or re-evaluate them. Keep it concise (under 120 words).
"""
        try:
            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt
            )
            brief = response.text.strip()
        except Exception as e:
            logger.error(f"Gemini brief generation failed: {e}")
            brief = (
                f"Safety evaluation complete (brief generation failed). Hard stop: {hard_stop}. "
                f"Triggered rules: {', '.join([r['code'] for r in triggered_rules]) if triggered_rules else 'none'}."
            )

    # 5. Generate advisory considerations (best practices relevant to event category)
    advisory_considerations = ""
    if not api_key:
        # Offline pre-defined fallbacks
        if event_type == "work_at_height":
            advisory_considerations = "- Inspect safety harnesses and anchorage points.\n- Verify scaffolding load capacity and guardrails.\n- Conduct a tool-box talk on fall prevention before starting work."
        elif event_type == "excavation":
            advisory_considerations = "- Verify shoring/trench shielding stability.\n- Monitor atmospheric hazards and soil water content.\n- Establish clear physical barriers and warning tape around trench perimeters."
        elif event_type == "toxic_gas":
            advisory_considerations = "- Check gas detection sensors and calibration logs.\n- Ensure active ventilation is functional.\n- Confirm personal respirators and emergency evacuation gear are ready."
        elif event_type == "extreme_weather":
            advisory_considerations = "- Monitor meteorological alerts hourly.\n- Secure loose materials and heavy equipment.\n- Cease high-risk outdoor tasks (like lifts or welding) immediately."
        else:
            advisory_considerations = "- Follow standard job safety analysis procedures.\n- Review contractor safety compliance logs.\n- Report any hazardous conditions to site supervisor."
    else:
        client = genai.Client(api_key=api_key)
        prompt_advisory = f"""
You are the Safety Agent for ConstructionOS AI.
Generate general construction-safety best-practice notes and advisory considerations relevant to a safety event of category: '{event_type}'.
Include 2-3 specific safety recommendations for site supervisors (e.g. equipment checks, safety briefings, weather monitoring).
Keep the advisory brief, professional, and structured as bullet points (under 80 words).
"""
        try:
            res_advisory = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt_advisory
            )
            advisory_considerations = res_advisory.text.strip()
        except Exception as e:
            logger.error(f"Gemini advisory considerations generation failed: {e}")
            # Fall back to standard offline template
            if event_type == "work_at_height":
                advisory_considerations = "- Inspect safety harnesses and anchorage points.\n- Verify scaffolding load capacity and guardrails."
            elif event_type == "excavation":
                advisory_considerations = "- Verify shoring/trench shielding stability.\n- Monitor atmospheric hazards."
            else:
                advisory_considerations = "- Follow standard job safety analysis procedures.\n- Report hazardous conditions."

    return {
        "hard_stop": hard_stop,
        "triggered_rules": triggered_rules,
        "brief": brief,
        "advisory_considerations": advisory_considerations,
        "advisory_disclaimer": _ADVISORY_DISCLAIMER,
        "fallback_mode_active": fallback_mode,
        "parse_error": False
    }
