import logging
import json
from typing import Dict, Any, List, Optional
from google import genai

from backend.agents.observe_agent import get_api_key
from backend.tools.cpm_engine import get_project_state
from backend.config import MODEL_NAME, use_mock_llm

# Configure logging
logger = logging.getLogger(__name__)

_ADVISORY_DISCLAIMER = (
    "Advisory considerations are general safety best practices generated by AI for "
    "informational purposes only. The regulatory hard stop status is derived deterministically "
    "from the ConstructionOS regulatory knowledge base rules and is not influenced by these advisories."
)

# ---------------------------------------------------------------------------
# Mock brief template — interpolates actual hard_stop + triggered_rules values
# at render time, preventing narrative/decision mismatches structurally.
# ---------------------------------------------------------------------------
def _mock_brief(
    event_type: str,
    severity: int,
    hard_stop: bool,
    triggered_rules: List[Dict[str, str]],
) -> str:
    """
    Generates a deterministic safety brief by interpolating real computed values
    (hard_stop, triggered_rules, event_type, severity) into a template.
    No canned per-scenario text — the template is the single source of truth.
    """
    stop_label = "HARD_STOP: TRUE (non-overridable halt)" if hard_stop else "HARD_STOP: FALSE (no halt required)"
    rules_text = (
        ", ".join(f"{r['code']}" for r in triggered_rules)
        if triggered_rules
        else "none"
    )
    rules_detail = (
        " ".join(f"[{r['code']}: {r['description']}]" for r in triggered_rules)
        if triggered_rules
        else "No regulatory rule triggered for this event category."
    )
    action = (
        "All site operations in the affected zone must cease immediately pending inspection and regulatory clearance."
        if hard_stop
        else "Operations may continue under standard site precautions. Monitor the situation and escalate if conditions deteriorate."
    )
    return (
        f"[MOCK] ConstructionOS Safety Assessment — Event: {event_type} | Severity: {severity}/10 | {stop_label} | "
        f"Rules triggered: {rules_text}. {rules_detail} {action}"
    )


# ---------------------------------------------------------------------------
# Mock advisory template — per event_type, no hard_stop dependency
# ---------------------------------------------------------------------------
_MOCK_ADVISORIES: Dict[str, str] = {
    "work_at_height": (
        "- Conduct immediate physical inspection of all harnesses, lanyards, and anchor points before any resumption.\n"
        "- Verify crane hoist mechanism and wire-rope integrity with a certified lifting equipment engineer.\n"
        "- Issue a site-wide toolbox talk covering fall-clearance calculations and emergency rescue protocol."
    ),
    "extreme_weather": (
        "- Monitor IMD/NDMA alerts hourly and do not resume work until wind speed drops below 45 km/h.\n"
        "- Secure all loose materials, scaffolding panels, and unsecured equipment immediately.\n"
        "- Issue weather-standdown memo to all contractors; log the stoppage in the site diary."
    ),
    "excavation": (
        "- Verify trench shoring and shielding stability before allowing personnel near excavation faces.\n"
        "- Conduct atmospheric hazard check (oxygen, CO, methane) at trench entry points.\n"
        "- Ensure physical barriers and warning tape are installed around all open excavation perimeters."
    ),
    "toxic_gas": (
        "- Confirm ventilation system is operational and air quality readings are within safe limits before re-entry.\n"
        "- Ensure all personnel have functioning PPE (respirators, gloves) available on-site.\n"
        "- Log the incident in the site safety diary and notify the site safety officer immediately."
    ),
}
_DEFAULT_ADVISORY = (
    "- Follow standard job safety analysis procedures.\n"
    "- Review contractor safety compliance logs.\n"
    "- Report any hazardous conditions to site supervisor."
)


def assess_safety(observe_output: Dict[str, Any], raw_event_text: Optional[str] = None) -> Dict[str, Any]:
    """
    Evaluates safety compliance by matching the event type against active regulatory rules.
    Issues a HARD_STOP if any matching rule is found.
    In mock mode (USE_MOCK_LLM=true), returns deterministic results with no API calls.
    Brief is always generated from a template interpolating actual hard_stop/triggered_rules values —
    never independently-authored canned text — to prevent narrative/decision mismatches structurally.
    """
    # 1. Handle upstream parse errors
    if observe_output.get("parse_error"):
        logger.warning("Safety assessment halted due to upstream parse error.")
        return {
            "hard_stop": False,
            "triggered_rules": [],
            "brief": "Safety assessment halted: Observe Agent failed to parse the event.",
            "advisory_considerations": "",
            "advisory_disclaimer": _ADVISORY_DISCLAIMER,
            "fallback_mode_active": False,
            "parse_error": True
        }

    event_type = observe_output.get("event_type")
    severity = observe_output.get("severity")

    # 2. Load active regulatory knowledge base rules (always deterministic — never mocked)
    state, fallback_mode = get_project_state()
    rules = state.get("regulatory_kb", [])

    # 3. Match rules based on trigger condition (deterministic — never mocked)
    triggered_rules = []
    for rule in rules:
        if rule.get("trigger_condition") == event_type:
            triggered_rules.append({
                "code": rule.get("code"),
                "description": rule.get("description")
            })

    # HARD_STOP is True if any rule trigger condition matches the event type.
    # WARNING: advisory_considerations must never influence hard_stop.
    hard_stop = len(triggered_rules) > 0

    # --- MOCK MODE: skip all Gemini calls, use templated brief + canned advisories ---
    if use_mock_llm():
        logger.info("[MOCK MODE] Safety Agent running without Gemini API call.")
        brief = _mock_brief(event_type, severity, hard_stop, triggered_rules)
        advisory_considerations = _MOCK_ADVISORIES.get(event_type, _DEFAULT_ADVISORY)
        return {
            "hard_stop": hard_stop,
            "triggered_rules": triggered_rules,
            "brief": brief,
            "advisory_considerations": advisory_considerations,
            "advisory_disclaimer": _ADVISORY_DISCLAIMER,
            "fallback_mode_active": fallback_mode,
            "parse_error": False
        }

    # 4. Generate explanation brief using Gemini (treating the decision as fixed facts)
    api_key = get_api_key()
    if not api_key:
        logger.warning("GEMINI_API_KEY not configured. Safety Agent using offline fallback brief.")
        brief = (
            f"Safety evaluation complete. Hard stop: {hard_stop}. "
            f"Triggered rules: {', '.join([r['code'] for r in triggered_rules]) if triggered_rules else 'none'}."
        )
    else:
        client = genai.Client(api_key=api_key)
        
        prompt = f"""
You are the Safety Agent for ConstructionOS AI.
Your task is to draft a compliance assessment brief explaining a safety event evaluation.

The safety evaluation results are already decided as fixed facts:
- HARD_STOP: {hard_stop} (if True, this is an absolute, non-overridable stop signal for operations)
- Triggered Rules: {json.dumps(triggered_rules)}
- Event Category: {event_type}
- Event Severity: {severity}/10

Raw Jobsite Report Context:
"{raw_event_text or 'No raw text provided.'}"

Please write a brief summary explaining these facts, emphasizing why a hard stop was or was not issued, and reference relevant regulatory norms (such as BOCW Act or Factories Act) as context.
WARNING: Your narrative must be entirely consistent with the fixed facts above (HARD_STOP is {hard_stop}). Do not contradict or re-evaluate them. Keep it concise (under 120 words).
"""
        try:
            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt
            )
            brief = response.text.strip()
        except Exception as e:
            logger.error(f"Gemini brief generation failed: {e}")
            brief = (
                f"Safety evaluation complete (brief generation failed). Hard stop: {hard_stop}. "
                f"Triggered rules: {', '.join([r['code'] for r in triggered_rules]) if triggered_rules else 'none'}."
            )

    # 5. Generate advisory considerations (best practices relevant to event category)
    advisory_considerations = ""
    if not api_key:
        advisory_considerations = _MOCK_ADVISORIES.get(event_type, _DEFAULT_ADVISORY)
    else:
        client = genai.Client(api_key=api_key)
        prompt_advisory = f"""
You are the Safety Agent for ConstructionOS AI.
Generate general construction-safety best-practice notes and advisory considerations relevant to a safety event of category: '{event_type}'.
Include 2-3 specific safety recommendations for site supervisors (e.g. equipment checks, safety briefings, weather monitoring).
Keep the advisory brief, professional, and structured as bullet points (under 80 words).
"""
        try:
            res_advisory = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt_advisory
            )
            advisory_considerations = res_advisory.text.strip()
        except Exception as e:
            logger.error(f"Gemini advisory considerations generation failed: {e}")
            advisory_considerations = _MOCK_ADVISORIES.get(event_type, _DEFAULT_ADVISORY)

    return {
        "hard_stop": hard_stop,
        "triggered_rules": triggered_rules,
        "brief": brief,
        "advisory_considerations": advisory_considerations,
        "advisory_disclaimer": _ADVISORY_DISCLAIMER,
        "fallback_mode_active": fallback_mode,
        "parse_error": False
    }
